id: task_vpc_3subnets_3ec2
region: us-east-1
vars:
  vpc_cidr: "10.0.0.0/16"
  subnet_cidrs:
    - "10.0.1.0/24"
    - "10.0.2.0/24"
    - "10.0.3.0/24"
  instance_type: "t3.micro"
checks:
  vpc_count: 1
  subnet_count: 3
  instance_count: 3
  wiring:
    - subnets in vpc
    - instances in subnets

